### PR TITLE
add wolfram

### PR DESCRIPTION
**Pull request by tommydroptables**
[I didn't leave a description so it's being hijacked by Chad now. Yes, I'm now self-aware.]

### CODE REVIEW

**Comment by ahatzz11** [comment]
meh, it probably has bugs.

**Comment by tommydroptables** [comment]
http://cdn.meme.am/instances/9689481.jpg

Hey look at me I'm stupid.

**Comment by ahatzz11** [comment]
Are you serious tom? You can't take 3 seconds to embed the image? you lazy pos.

**Comment by tommydroptables** [comment]
lol can you embed an image into github?

I AM SO DUMB

On Fri, Dec 11, 2015 at 1:42 PM, Alex Hatzenbuhler <notifications@github.com

**Pull request merged**
